### ISSUE TITLE
source giscube-install-local.sh

### ISSUE THREAD

**Issue by abusquets** [giscube/giscube-server-ansible#2]
source giscube-install-local.sh not runs correctly.

I changed the two firts lines by 
# !/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

And runs correctly.

**Comment by manelclos** [comment]
What is the original error? can you show the command you are executing?

**Comment by abusquets** [comment]
sh giscube-install-local.sh
