### ISSUE TITLE
Postgres start fails

### ISSUE THREAD

**Issue by abusquets** [giscube/giscube-server-ansible#3]
I suggest add in README that is necessary have locale generated

sudo locale-gen en_US.UTF-8
or in may case locale-gen ca_ES.UTF-8

Related:

http://solutions4linux.blogspot.com.es/2014/09/solving-no-postgresql-clusters-exist.html

**Comment by manelclos** [comment]
Should be done with ansible, PR welcome!

**Comment by manelclos** [comment]
giscube-base-server will not generate and set a default locale, see https://github.com/giscube/giscube-base-server-ansible/commit/8609037ec5c872a4caa1990a1d0f873c7b409ac2

Can you try to reproduce again?

**Comment by manelclos** [comment]
inactive, closing

**Comment by manelclos** [comment]
inactive, closing

**Comment by manelclos** [comment]
inactive, closing

**Comment by manelclos** [comment]
inactive, closing

**Comment by manelclos** [comment]
inactive, closing

**Comment by manelclos** [comment]
inactive, closing

**Comment by manelclos** [comment]
inactive, closing

**Comment by manelclos** [comment]
inactive, closing

**Comment by manelclos** [comment]
inactive, closing

**Comment by manelclos** [comment]
inactive, closing
